## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha1_broker.yaml
- _v1alpha1_submariner.yaml
- _v1alpha1_servicediscovery.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
